# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Testing RKC.SGVP.Back

on:
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Test with Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - run: npm ci
      - run: npm test

  run-linters:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write

    steps:
      - name: Check out Git repository
      - uses: actions/checkout@v2

      - name: Run linters
      - uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true
